'use client';
import type { Metadata } from "next";
import "@/app/globals.css";
import { Provider } from "react-redux";
import store from "@/store/store";

/* export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className="bg-gray-200">{children}</body>
      </html>
    </Provider>
  );
}
