import "@/app/globals.css";
import { Roboto } from '@next/font/google';

export const metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
}; 

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={`${roboto.className} bg-gray-200`}>{children}</body>
      </html>
  );
}
